#.yml file for Gitlab-CI support

stages:
- build
- test
- deploy
- package

# build_debian:
#   stage: build
#   tags:
#     - debian
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
#     - make

# build_solaris:
#   stage: build
#   tags:
#     - solaris
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
#     - make

# build_redhat:
#   stage: build
#   tags:
#     - redhat
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
#     - make

build_osx:
  stage: build
  tags:
    - osx
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
    - make

# build_windows:
#   stage: build
#   tags:
#     - windows
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=OFF -DTEST_SWITCH=ON -G "Visual Studio 14 2015 Win64" ../
#     - cmake --build . --config Release

build_core:
  stage: build
  tags:
    - core
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=OFF -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
    - make -j8
  artifacts:
    paths:
    - build/

# test_debian:
#   stage: test
#   tags:
#     - debian
#   script:
#     - ctest

# test_solaris:
#   stage: test
#   tags:
#     - solaris
#   script:
#     - ctest

# test_redhat:
#   stage: test
#   tags:
#     - redhat
#   script:
#     - ctest

test_osx:
  stage: test
  tags:
    - osx
  script:
    - ctest

# test_windows:
#   stage: test
#   tags:
#     - windows
#   script:
#     - ctest

test_core:
  stage: test
  tags:
    - core
  script:
    - ctest
  dependencies:
    - build_core

# deploy_debian:
#   stage: deploy
#   tags:
#     - debian
#   script:
#     - make install

# deploy_solaris:
#   stage: deploy
#   tags:
#     - solaris
#   script:
#     - make install

# deploy_redhat:
#   stage: deploy
#   tags:
#     - redhat
#   script:
#     - make install

deploy_osx:
  stage: deploy
  tags:
    - osx
  script:
    - make install

# deploy_windows:
#   stage: deploy
#   tags:
#     - windows
#   script:
#     - make install

deploy_core:
  stage: deploy
  tags:
    - core
  script:
    - make install
  dependencies:
    - build_core

# package_debian:
#   stage: package
#   tags:
#     - debian
#   script:
#     - make package

# package_solaris:
#   stage: package
#   tags:
#     - solaris
#   script:
#     - make package

# package_redhat:
#   stage: package
#   tags:
#     - redhat
#   script:
#     - make package

package_osx:
  stage: package
  tags:
    - osx
  script:
    - make package

# package_windows:
#   stage: package
#   tags:
#     - windows
#   script:
#     - make package

package_core:
  stage: package
  tags:
    - core
  script:
    - make package
  dependencies:
    - build_core