stages:
- build
- test
- deploy

build_debian:
  stage: build
  tags:
    - debian
  script:
    - ./build.sh -evx
  artifacts:
    paths:
    - build/

#build_debian_swig:
#  stage: build
#  tags:
#    - debian
#  script:
#    - ./build.sh -ev

test_debian:
  stage: test
  tags:
    - debian
  script:
    - ./build.sh -evxt
  dependencies:
  - :build_debian

#test_debian_swig:
#  stage: test
#  tags:
#    - debian
#  script:
#    - ./build.sh -evt

#build_solaris:
#  stage: build
#  tags:
#    - solaris
#  script:
#    - ./build.sh -evx

#test_solaris:
#  stage: test
#  tags:
#    - solaris
#  script:
#    - ./build.sh -evxt

#build_redhat:
#  stage: build
#  tags:
#    - redhat
#  script:
#    - ./build.sh -evx -- -DC03_SWITCH=ON
#  artifacts:
#    paths:
#    - build/

#build_redhat_swig:
#  stage: build
#  tags:
#    - redhat
#  script:
#    - ./build.sh -ev -- -DC03_SWITCH=ON

#test_redhat:
#  stage: test
#  tags:
#    - redhat
#  script:
#    - ./build.sh -evxt -- -DC03_SWITCH=ON
#  dependencies:
#  - :build_redhat

#test_redhat_swig:
#  stage: test
#  tags:
#    - redhat
#  script:
#   - ./build.sh -evt -- -DC03_SWITCH=ON

build_osx:
  stage: build
  tags:
    - osx
  script:
    - ./build.sh -evx
  artifacts:
    paths:
    - build/

test_osx:
  stage: test
  tags:
    - osx
  script:
    - ctest
  dependencies:
  - :build_osx

build_osx_swig:
  stage: build
  tags:
    - osx
  script:
    - ./build.sh -ev
  artifacts:
    paths:
    - build/

test_osx_swig:
  stage: test
  tags:
    - osx
  script:
    - ctest
  dependencies:
  - :build_osx_swig

build_windows:
  stage: build
  tags:
    - windows
  script:
    - build.sh -evx
  artifacts:
    paths:
    - build/

test_windows:
  stage: test
  tags:
    - windows
  script:
    - ctest
  dependencies:
  - :build_windows