#.yml file for Gitlab-CI support

stages:
- build
- test

cache:
  paths:
  - build/

build_debian:
  stage: build
  tags:
    - debian
  script:
    - ./build.sh -evx

build_debian_swig:
  stage: build
  tags:
    - debian
  script:
    - ./build.sh -ev

test_debian:
  stage: test
  tags:
    - debian
  script:
    - ./build.sh -evxt

test_debian_swig:
  stage: test
  tags:
    - debian
  script:
    - ./build.sh -evt

build_solaris:
  stage: build
  tags:
    - solaris
  script:
    - ./build.sh -evx

test_solaris:
  stage: test
  tags:
    - solaris
  script:
    - ./build.sh -evxt

build_redhat:
  stage: build
  tags:
    - redhat
  script:
    - ./build.sh -evx -- -DC03_SWITCH=ON

build_redhat_swig:
  stage: build
  tags:
    - redhat
  script:
    - ./build.sh -ev -- -DC03_SWITCH=ON

test_redhat:
  stage: test
  tags:
    - redhat
  script:
    - ./build.sh -evxt -- -DC03_SWITCH=ON

test_redhat_swig:
  stage: test
  tags:
    - redhat
  script:
   - ./build.sh -evt -- -DC03_SWITCH=ON

build_osx:
  stage: build
  tags:
    - osx
  script:
    - ./build.sh -evx

test_osx:
  stage: test
  tags:
    - osx
  script:
    - ctest

build_osx_swig:
  stage: build
  tags:
    - osx
  script:
    - ./build.sh -ev

test_osx_swig:
  stage: test
  tags:
    - osx
  script:
    - ctest

build_windows:
  stage: build
  tags:
    - windows
  script:
    - build.sh -evx

test_windows:
  stage: test
  tags:
    - windows
  script:
    - ctest
