#.yml file for Gitlab-CI support

stages:
- build
- test
- deploy
- package

# build_debian:
#   stage: build
#   tags:
#     - debian
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
#     - make

build_solaris:
  stage: build
  tags:
    - solaris
  script:
   - ./build.sh -evx

# build_redhat:
#   stage: build
#   tags:
#     - redhat
#   script:
#     - mkdir build
#     - cd build
#     - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
#     - make

build_osx:
  stage: build
  tags:
    - osx
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=ON -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
    - make
  artifacts:
    paths:
    - build/

build_windows:
  stage: build
  tags:
    - windows
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=install -DBUILD_EXT=ON -DBUILD_PYTHON=OFF -DTEST_SWITCH=ON -G "Visual Studio 14 2015 Win64" ../
    - cmake --build . --config Release
  artifacts:
    paths:
    - build/

build_core:
  stage: build
  tags:
    - core
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_INSTALL_PREFIX=$HOME/.local -DCMAKE_INSTALL_PREFIX=$HOME/.local/gpstk -DBUILD_EXT=OFF -DBUILD_PYTHON=ON -DTEST_SWITCH=ON ../
    - make -j8
  artifacts:
    paths:
    - build/

# test_debian:
#   stage: test
#   tags:
#     - debian
#   script:
#     - ctest

test_solaris:
  stage: test
  tags:
    - solaris
  script:
    - ./build.sh -evxt

# test_redhat:
#   stage: test
#   tags:
#     - redhat
#   script:
#     - ctest

test_osx:
  stage: test
  tags:
    - osx
  script:
    - cd build
    - ctest
  dependencies:
    - build_osx

test_windows:
  stage: test
  tags:
    - windows
  script:
    - cd build
    - cmake --build . --target RUN_TESTS --config Release
  dependencies:
    - build_windows
  allow_failure: true

test_core:
  stage: test
  tags:
    - core
  script:
    - cd build
    - ctest
  dependencies:
    - build_core
  allow_failure: true

# deploy_debian:
#   stage: deploy
#   tags:
#     - debian
#   script:
#     - make install

# deploy_solaris:
#   stage: deploy
#   tags:
#     - solaris
#   script:
#     - make install

# deploy_redhat:
#   stage: deploy
#   tags:
#     - redhat
#   script:
#     - make install

deploy_osx:
  stage: deploy
  tags:
    - osx
  script:
    - cd build
    - make install
  dependencies:
    - build_osx

deploy_windows:
  stage: deploy
  tags:
    - windows
  script:
    - cd build
    - cmake --build . --config Release --target install
  dependencies:
    - build_windows

deploy_core:
  stage: deploy
  tags:
    - core
  script:
    - cd build
    - make install
  dependencies:
    - build_core
  allow_failure: true

# package_debian:
#   stage: package
#   tags:
#     - debian
#   script:
#     - make package

# package_solaris:
#   stage: package
#   tags:
#     - solaris
#   script:
#     - make package

# package_redhat:
#   stage: package
#   tags:
#     - redhat
#   script:
#     - make package

package_osx:
  stage: package
  tags:
    - osx
  script:
    - cd build
    - make package
  dependencies:
    - build_osx

package_windows:
  stage: package
  tags:
    - windows
  script:
    - cd build
    - cpack -C Release
  dependencies:
    - build_windows

package_core:
  stage: package
  tags:
    - core
  script:
    - cd build
    - make package
  dependencies:
    - build_core
  allow_failure: true